### ISSUE TITLE
Exception when RecyclerView has no items (removable items)

### ISSUE THREAD

**Issue by haithamsboui** [SouthernBox/ParallaxRecyclerView#1]
I'm having a recyclerView with removable items , the exception is raised when I delete all the items from the list but not when I initialise it with 0 items . 
Here's the stacktrace 

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.app, PID: 6768
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference
                                                                      at com.southernbox.parallaxrecyclerview.ParallaxRecyclerView$2.onScrolled(ParallaxRecyclerView.java:76)
                                                                      at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4722)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3789)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3421)
                                                                      at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1710)
                                                                      at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:346)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by NanBox** [comment]
Thank you for your feedback.
